name: Example Workflow

on:
  push:
    branches:
      - testaction

jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      - name: Print to Log
        id: print-to-log
        uses: mdelgert/hello-world-docker-action@main
        with:
          who-to-greet: ${{ inputs.who-to-greet }}